# Build the runtime image
FROM mcr.microsoft.com/dotnet/aspnet:8.0

ARG RELEASE_DIR

LABEL org.opencontainers.image.source=https://github.com/Kaleido-organisation-manager/kaleido-modules-services-grpc-currency-rates
LABEL org.opencontainers.image.description="Container image for the Kaleido Modules Services Grpc Currency Rates"

ENV "Kestrel:EndpointDefaults:Protocols"="Http2"

WORKDIR /app
COPY ${RELEASE_DIR} .
ENTRYPOINT ["dotnet", "Kaleido.Modules.Services.Grpc.CurrencyRates.dll"]